### ISSUE TITLE
@babel/plugin-transform-optional-chaining， configuration does not take effect

### ISSUE THREAD

**Issue by Lhhpw0204** [babel/babel-loader#1008]
In the typescript file, optional chain syntax is used. 
After being compiled by ts-loader, and then processed by babel-loader, the optional chain syntax still exists in the packaged js file.

You can view it via the link below：
https://codesandbox.io/p/sandbox/empty-cache-79clq2?file=%2Fwebpack.config.js%3A21%2C6-21%2C47

**Comment by nicolo-ribaudo** [comment]
If you build for development and not production (thus without a minifier) you'll see that optional chain is properly compiled.

I think the problem is that terser is undoing Babel's compilation to generate smaller code.

As an experiment, you can try replacing your input code with the following:
```js
const obja = {
  foo: {
    bar: {
      baz: 42,
      _name: "FUTU COM",
    },
  },
};

const _baz = obja === null || obja === void 0 ? void 0 : obja.foo;

console.log(_baz, "_baz2223================");

const say = () => {
  console.log("hello world");
};
say();

export {};
```

it contains no optional chaining, but the output code still does. I suggest asking in https://github.com/webpack/webpack/discussions how to disable this specific minifier optimization.
