### ISSUE TITLE
Backticks in es6 imports/exports and jsx attributes throws error

### ISSUE THREAD

**Issue by kibin** [babel/babel-loader#140]
I don’t know if this is by intention, but this throws exception:
```
Module build failed: SyntaxError: /Users/al/projects/js/account-cycle/src/index.js: Unexpected token (1:18)
> 1 | import Cycle from `@cycle/core`
```
Same for jsx attributes like ```<input type=`submit` />```.

I think that template strings (especially one-liners without any interpolation) shouldn’t throw. Am I missing something?

**Comment by Lonelind** [comment]
jsx template strings should be wrapped in curly braces: ```<input type={`submit`} />```.

**Comment by kibin** [comment]
Yeah, I know that with curly braces it will work, my main question here is why don’t curly braces treated as string literals?

**Comment by pewh** [comment]
+1. Need this very much!

**Comment by pewh** [comment]
I think from ES6 standard, this way will never be supported. I also have try something like `import foo from 'bar/' + '123'` and it doesn't work. So, my working solution is use backtick on `require`.

Ex: ```const foo = require(`bar/${123}`)```

**Comment by loganfsmyth** [comment]
For the JSX case, the answer is "because that is what the spec says", if you want support for them you would need to bring that up with Facebook.

For the import case, the answer is that they code must be statically-readable. An environment must be able to know exactly which paths a file depends on _before_ executing the files, and template strings, in the general case, require evaluation before knowing what the path is. That could technically be special-cased to disallow interpolation, but at that point it's easier and avoids spec complexity to just require normal strings.
