### ISSUE TITLE
Promise Polyfill for BlueBird: with Babel 6 is this still a thing?

### ISSUE THREAD

**Issue by dtothefp** [babel/babel-loader#143]
From what I've read about Babel 6 it looks like the `runtime` is no longer supported. Wondering if the suggested polyfill in the readme is still the correct approach?

``` js
require('babel-runtime/core-js/promise').default = require('bluebird');
```

**Comment by Dashed** [comment]
See: https://github.com/babel/babel-loader/issues/23#issuecomment-155274041

The `README` would need to be updated to accommodate 3rd-party polyfilling with babel 6.x/webpack.

**Comment by Dashed** [comment]
@dtothefp I've made the switch to babel 6.x, and I can confirm that the suggested polyfill still works.

**Comment by gbrassey** [comment]
is there a way to do this without bootstrapping the entry file?

**Comment by Dashed** [comment]
I've yet to find a way to avoid the bootstrap step.

If you *really* want to avoid it, one would need to fork `babel-plugin-transform-runtime` and bypass the necessary overrides: https://github.com/babel/babel/blob/917436ca2427a4d751d369ecc887e8889a9a047e/packages/babel-plugin-transform-runtime/src/index.js#L40-L45

**Comment by jeromecovington** [comment]
If I prefer to use `bluebird` as my `Promise` implementation of choice in Node, is there a way to declare this without needing to add the `require` statement from this issue description in every file that uses `Promise`?

**Comment by steida** [comment]
@jeromecovington Override it via global. Check https://github.com/este/este/blob/74509386fa8af6fade64045c857dadcbb88d8e72/src/server/index.js#L20

**Comment by juanstiza** [comment]
Hi, I'm reviewing using babel for the first time on a production project. What is the difference between this and using `import Promise from 'bluebird'`? Is it just to avoid doing this?

**Comment by vphantom** [comment]
@juanstiza The advantage of an early `global.Promise = bluebird` is that it only needs to be done _once_ in an entire project and it also guarantees that all dependencies use Bluebird.

**Comment by juanstiza** [comment]
Nice. But for that to work I need to `require` babel onto my codebase, isn't it so?

**Comment by vphantom** [comment]
Yes sorry, the one-liner would be something like `global.Promise = require('bluebird')` if you prefer.

**Comment by juanstiza** [comment]
Great! thanks!

**Comment by loganfsmyth** [comment]
I know it makes things easier, but modifying globals is a good way to make a maintenance nightmare for yourself in the future if you ever decide you want to change, since you'll have absolutely no idea which promise uses in your codebase only require standard ES6 features and which require Bluebird-specific functions. Shadowing globals is also a bad idea, better to do

    import Bluebird from 'bluebird';

then use that where you actually need it.

**Comment by vphantom** [comment]
@loganfsmyth Like I said, the global ensures that some dependency isn't using the ES6 implementation in parallel with Bluebird's. There is a performance downside to running ES6's. It is obviously good practice to _additionally_ require Bluebird explicitly in your own modules that need its non-standard features, but it's a stretch to say that forcing it globally per se is a bad idea.

**Comment by loganfsmyth** [comment]
> the global ensures that some dependency isn't using the ES6 implementation in parallel

That's essentially my fear, because overriding the global means any module you use that returns promises starts returning Bluebird-based promises, so if you load it globally, it'd be extremely easy to do

    require('some-api').getThing().spread(function(foo, bar) {});

Assuming this module just returns `Promise.resolve(4)` or something, it's easy to not realize that this code is now relying on the fact that you've overridden the global to make `.spread` available. You've created an implicit dependency between this call, and some other place in your codebase where you override the global. To me, this isn't something I'd want, but it's also very hard to catch without extensive code review.

I don't think I'd mind if Bluebird exposed an alternate that was fast without adding nonstandard methods, like

    global.Promise = require('bluebird/es6');

or something.

Anyway, if you're gonna do this, it's obviously entirely your call, but I wanted to give a counterpoint. There are potential maintainability concerns with this approach that worry me.

**Comment by juanstiza** [comment]
I agree, it is entirely my call. In my particular case I have some legacy code written in ES5 using Bluebird which I want to include and perhaps re-code in ES6. Bluebird is, then, an arbitrary decision and perhaps, with good documentation there shouldn't be much problem. We aren't writing an external library, it is purely internal and Bluebird has always been the choice. Anyhow, thanks again!

**Comment by geelen** [comment]
This seems to work so far for me: https://github.com/chpio/babel-plugin-transform-promise-to-bluebird

Just put it ahead of `transform-runtime`. It rewrites usages of `Promise` to `bluebird` and adds an import. Feels like the right place to be injecting the override, to my eyes.

**Comment by dashed** [comment]
There are a lot of good options/arguments/opinions for how bluebird shall be polyfilled appropriately in projects.  I think someone should put some suggestions on the `README.md`: https://github.com/babel/babel-loader#custom-polyfills-eg-promise-library

**Comment by extg** [comment]
If you are using [babel-plugin-transform-runtime](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-runtime)

```js
plugins: [
        new webpack.NormalModuleReplacementPlugin(/babel-runtime\/core-js\/promise/, 'bluebird')
    ],
```

**Comment by loganfsmyth** [comment]
I think realistically at this point, in-place swapping Bluebird for native promises is a mistake. If you want to do it, you can, but it's not something I'd recommend. If you want to convert a native promise to a Bluebird promise, you can always use `Bluebird.resolve(p)` to get one.
