### ISSUE TITLE
Disabling source maps

### ISSUE THREAD

**Issue by Naddiseo** [babel/babel-loader#18]
How do I disable the source map that 6to5 generates, but allow the general webpack one?

**Comment by sebmck** [comment]
Looks like `6to5-loader` finds out whether to include source maps or not via [this](https://github.com/6to5/6to5-loader/blob/master/index.js#L24) line.

**Comment by Naddiseo** [comment]
Yeah, I saw that, but I don't know how to set it. In my `webpack.config.js` I have my loader options as:
`loader: '6to5-loader?{"runtime":true,"modules":"common","blacklist":["react"],"sourceMaps":"false"}'`
But that doesn't seem to work.

**Comment by Couto** [comment]
Webpack uses a querystring like style to pass options to loaders.
You should do something like:

`loader: '6to5?runtime&modules=common&blacklist[]=react&!-sourcemaps`

You can find more info on how to use options with webpack loaders here: https://github.com/webpack/loader-utils

**Comment by Couto** [comment]
Uh. Took a deeper inspection (or better reading) and your way of passing options is fine. My bad.

However the sourceMap option should be singular not plural.
Still I need to take a better look to compare both source maps.

**Comment by Naddiseo** [comment]
@Couto, using sourceMap or sourceMaps doesn't work. The suggested querystring style also doesn't work as given, and removing the "!" yields errors from the source-map module (I also tried with variations of case and plurality all with errors).

So far the only way I've found that works is to manually set `options.sourceMap` to false in 6to5-loader, which is far from ideal.

**Comment by grrowl** [comment]
> yields errors from the source-map module

Our build servers just updated to webpack 0.5.0 (and its source-maps dependency) and this is breaking everything. Is there no way to set `this.sourceMaps` from options ?

**Comment by sebmck** [comment]
Not sure what the specific issue is if someone can elaborate it'd be great. ie. why it's an issue and why webpack isn't supplying the correct `sourceMap` option.

**Comment by Couto** [comment]
Also can you confirm your webpack version please? the current version of webpack is 1.7.2, so I find your version kinda odd.

**Comment by Rob-ot** [comment]
It looks like babel-loader ignores any sourceMap options you pass in the 'loader' line, it just checks to see if webpack wants a sourceMap and forwards that option. Webpack sourcemaps are enabled with the devtool param (as you probably already know).

Maybe the right thing to do for this issue is to have the 'loader' sourceMap option override the global webpack option. e.g. changing

https://github.com/babel/babel-loader/blob/master/index.js#L31

to

`if (options.sourceMap === undefined) options.sourceMap = this.sourceMap;`

but keep in mind that turning on sourcemaps there won't work unless sourcemaps are turned on for webpack also.

**Comment by Naddiseo** [comment]
@Rob-ot that fix solves my problem.

**Comment by d3viant0ne** [comment]
Resolving this as the fix mentioned has since been implemented in another feature - https://github.com/babel/babel-loader/blob/master/index.js#L55-L57
