### ISSUE TITLE
Load plugins directly and not with a path string

### ISSUE THREAD

**Issue by AugustBrenner** [babel/babel-loader#274]
I am currently doing:
`plugins: [
    path.resolve(__dirname, 'scripts', 'babelRelayPlugin.js'),
    'transform-runtime'
]`

which works fine. 

I would prefer however to do the following and just inject the content of babelRelayPlugin.js directly into the babel-loader:

`plugins: [
    babelRelayPlugin(require('./src/data/schema.json').data),
    'transform-runtime'
]`

however this will throw an error.

Is there any way to do something like this with babel loader, and if not, can there be in the future?

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babel-loader. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.

In your specific case, it seems like passing a function would normally work, so it's hard to say since you didn't say what the error was.
