### ISSUE TITLE
Compilation never finishes when using devtool: 'source-map'

### ISSUE THREAD

**Issue by robrichard** [babel/babel-loader#31]
I have a large project (~23 entry files) and I am using babel-loader. When I compile with "eval-source-map" it takes about 45 seconds to complete. When I use 'source-map' (for production builds), I canceled it after 2 hours. My project doesn't have many node_modules, mostly one large library that we do want to be transpiled.

**Comment by Couto** [comment]
I would suggest to transpile your large library before publishing it, so that you can ignore all node modules, or at least refine the exclude regex so that you ignore every node module except your library.

At first though I believe that the problem lies within webpack itself. Can I ask you to make a build without babel-loader, but with source-maps, just to check the time? I'm guessing it's faster obviously and the result would be unusable, but it's only to get an idea on the duration of your build step.

**Comment by sebmck** [comment]
Are you including `node_modules` and do you have any really large single files (~2MB etc)?

**Comment by robrichard** [comment]
@Couto, without babel loader, but with source maps the build is a little under 2 minutes

**Comment by sebmck** [comment]
>  mostly one large library that we do want to be transpiled.

How big is that file?

**Comment by robrichard** [comment]
It's several hundred small files, none of them are very large

**Comment by d3viant0ne** [comment]
@robrichard - Is this still an issue on babel-core 6 / babel-loader@latest or can I resolve this?

**Comment by robrichard** [comment]
not an issue any more, closing
