### ISSUE TITLE
typeof process.env.BABLE_ENV String

### ISSUE THREAD

**Issue by kagawagao** [babel/babel-loader#383]
## **BEFORE YOU SUBMIT** please read the following:

**I'm submitting a bug report**

**Webpack Version:**
2.2.1

**Babel Core Version**:
6.23.1
**Babel Loader Version**:
6.3.1

**Please tell us about your environment:**
OSX 10.12.3

**Current behavior:**

in the latest version of `babel-loader`, the code follow may cause error:
```javascript

const env = userOptions.forceEnv || process.env.BABEL_ENV || process.env.NODE_ENV;
console.log(process.env.BABEL_ENV) // output: undefined
console.log(typeof process.env.BABEL_ENV) // output: string

```

**Expected/desired behavior:**

`process.env.NODE_ENV` could take effect

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.**

use latest version of `babel-loader`

* **What is the expected behavior?**
see above

* **What is the motivation / use case for changing the behavior?**

`process.env.NODE` could take effect when no `BABEL_ENV`

**Comment by danez** [comment]
Sorry, I don't get what the exact problem is here. I fixed an issue with envs in 6.3.2. Can you please try if this resolves your problem?

**Comment by kagawagao** [comment]
I may not have described it clearly 😅
In the version `6.3.1`, the type of `process.env.BABEL_ENV` is `string`, so the `NODE_ENV` could not take effect, but now, it is `undefined` when no `BABEL_ENV` config, you fix it.

**Comment by Wildhoney** [comment]
@danez because this bit us too, I'd just like to point out a little something.

In [the change](https://github.com/babel/babel-loader/commit/fdf0184bb607f980e517e617b2c425343c244eee) for `6.3.1` it seems as though its intention was to add a backwards-compatible feature, however you incremented the patch version, instead of the minor version, which to me isn't how you handle version changes in semver.

In our build we lock to `6.3.x` and allow any bug fixes to be included in the build for development tools only. Of course you could have pushed a backwards-compatible bug fix by incrementing patch and it still could have broken, but it's just slightly annoying that we were caught out when the patch version in this instance should not have been incremented.
