### ISSUE TITLE
Polyfill

### ISSUE THREAD

**Issue by arcanis** [babel/babel-loader#45]
Hi,

What is currently the best way to bundle the Babel polyfill when compiling bundles ? Shouldn't babel-loader do it automatically when using the experimental flag (or at least have an option to bundle it in the entry points) ?

I mainly ask because async functions do not work without the regenerator runtime.

**Comment by sebmck** [comment]
Follow [this](https://github.com/babel/babel-loader#babel-is-injecting-helpers-into-each-file-and-bloating-my-code) solution in the `babel-loader` FAQ or see the Babel website for docs on the [polyfill](http://babeljs.io/docs/usage/polyfill) and [runtime](http://babeljs.io/docs/usage/runtime/).

**Comment by arcanis** [comment]
I had success with the following :

```
module.exports = {
    entry : {
        main : [
            __dirname + '/node_modules/babel-core/browser-polyfill.js'
        ]
    },
    module : {
        noParse : [
            /\/babel-core\/browser-polyfill\.js$/
        ]
    }
};
```

**Comment by nlutterman** [comment]
I don't want to include the file as an entry point, and I do not want to use the runtime.  I also do not wish to use a <script> tag.  I want the file built into the rest of my bundle.

There is no clear explanation as to how to include the actual polyfill file.  The documentation in the official Babel site lists linking a script tag or using `require()`.

I would like to simply include the file in webpack, prepended, before everything else.  Is this possible using the babel-loader?

Otherwise I'll have to manually include the polyfill in the webpack config.

**Comment by damienklinnert** [comment]
@arcanis solution worked for me!
