### ISSUE TITLE
Share cache with babel-register?

### ISSUE THREAD

**Issue by jakepusateri** [babel/babel-loader#462]
**I'm submitting a feature request**
Would it be possible/desired to have babel-loader and babel-register share the same cache?

babel-loader uses cacheDirectory, which stores cached files in .json.gz files

babel-register uses BABEL_CACHE_PATH, which stores cached files all together in a .json file.

Is one approach better than another? Should they try and converge at all?

**Webpack Version:**
1.15.0

**Babel Core Version**:
6.24.1

**Babel Loader Version**:
6.4.1

**Please tell us about your environment:**
OSX 10.x / Linux

**What is the motivation / use case for changing the behavior?**
During my build, babel is being used twice, once from babel-register via a mocha compiler, and once from babel-loader. Having this step happen only once would reduce build times by approximately 30 seconds.

**Comment by Couto** [comment]
IMHO, while I'm sure it's possible to implement this, I believe that is not trivial.

babel-loader stores several files with some meta information (https://github.com/babel/babel-loader/blob/master/src/index.js#L127-L136) as the filename, but it seems to me (by glancing at the code) that babel-register takes a different approach, where it stores a really big object with several files inside.

I think that this idea would provide a nice discussion, but probably on the babel-core package, since it's  the central point for all plugins/loaders/tools... :)

**Comment by loganfsmyth** [comment]
I think it will depend on the plugins being used whether or not cache entries could be shared between `babel-loader` and `@babel/register`, but I've at least filed https://github.com/babel/babel/issues/8605 to explore sharing more of the logic itself so more tooling can take advantage of caching.
