### ISSUE TITLE
sourceMap mapping incorrectly on babel-loader

### ISSUE THREAD

**Issue by xiachaoxulu** [babel/babel-loader#507]
## **BEFORE YOU SUBMIT** please read the following:

**I'm submitting a bug report**

**Webpack Version:**
^2.3.3

**Babel Core Version**:
^6.23.0

**Babel Loader Version**:
^6.4.1

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**

sourceMap mapping incorrectly on babel-loader

**Expected/desired behavior:**

correct

there has demo
https://github.com/xiachaoxulu/sourceMapDemo

**Comment by wxlworkhard** [comment]
I have the same problem

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babel-loader. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.

In this case, I'm going to guess that this should be fixed with https://github.com/vuejs/vue-loader/issues/1163#issuecomment-384712864
