### ISSUE TITLE
warn if options is provided and babelrc is not provided

### ISSUE THREAD

**Issue by brigand** [babel/babel-loader#509]
Edit: Sorry, pressed enter by mistake. Fixed.

*Delete what isn't applicable below*
**I'm submitting a feature request**

**Webpack Version:**
3.5.5

**Babel Core Version**:
6.7.2

**Babel Loader Version**:
6.2.4

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**

The 'babelrc' option is optional, and it isn't mentioned in the babel-loader docs. I now know it's in the babel docs, but that wasn't obvious to me.

**Expected/desired behavior:**

A warning should be printed if there is an 'options' object that contains 'preset', 'plugins', or 'env' keys and no 'babelrc' option. Most of the time you'd want to disable babelrc if you're configuring it in webpack.

I have my .babelrc mainly for scripts that run in babel-node, and it has to enable the es6 modules transform, while I don't want that in webpack. I lost some time to figuring this out.

**Comment by brigand** [comment]
Issue updated.

**Comment by g0t4** [comment]
How about just warn if you use both .babelrc file and webpack loader options (preset, plugins, etc) in webpack config? 

Otherwise this will discourage using webpack loader options for babel.

**Comment by loganfsmyth** [comment]
With Babel 7's new intelligent merging, it's entirely possible for `plugins` items in a Webpack config to be merged in with items from a `.babelrc` or `babel.config.js` in a smart way. Given that, I don't think I'd support erroring in this case. I also think it is hard to draw a clean line here, because there are still plenty of options that might make sense to pass directly to `babel-loader` independent of config file usage, so we'd have to have a specific whitelist of things to error one, which would be equally confusing.
