### ISSUE TITLE
[feature request] include dynamic import syntax plugin automatically

### ISSUE THREAD

**Issue by hzoo** [babel/babel-loader#515]
I've written/talked about this before a few times, might as well make it an issue.

We shouldn't have to ask users to include the dynamic import plugin if webpack is supporting it and is a source of pain. Ideally it would work with preset-env where webpack is it's own target or something but this is already babel-loader so we know that a user is using webpack + babel together. We could just make it a dependency (or just use `parserOpts: { plugins: ['dynamicImport'] }` and no dependency necessary).

So like at https://github.com/babel/babel-loader/blob/1ca5c7856d2129a28d6ba031bd8a5759aa80b8eb/src/index.js#L128-L129

```diff
const defaultOptions = {
+  parserOpts: { plugins: ['dynamicImport'] },
```

Or we'd have to do append the plugin to the end of the `plugins`: 

```js
options.plugins.push(require('babel-plugin-syntax-dynamic-import'))
```

**Comment by DrewML** [comment]
I can't think of a reason _not_ to do this, since the current version only supports `webpack` versions  >= 2

**Comment by mikeaustin** [comment]
This wa a source of pain for me because I was using the Webpack version of the plugin vs the Babel version. I was pulling out my hair tying to get the webpackChunkName comment to work. Then there’s the \@babel namespace that you should use for some modules because they’ve been moved. In general, I find it hard to find the right module sometimes because of similar names, clones, and name spacing. Of course that’s a whole topic on its own :)

**Comment by thiagoarrais** [comment]
Just started a PR for this. Can someone please help me get it merged?

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/10109
