### ISSUE TITLE
webpack install issues

### ISSUE THREAD

**Issue by 0nePoint0ne** [babel/babel-loader#632]
C:\Users\Gregory\my-app>npm start

> myapp@0.1.0 start C:\Users\Gregory\my-app
> webpack --config webpack.config.js

Hash: 2a24feeca2c63f84b11b
Version: webpack 4.12.1
Time: 130ms
Built at: 2018-06-26 11:02:00
 1 asset
[0] ./src/app/App.js 258 bytes {0} [built] [failed] [1 error]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'dev
elopment' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./src/app/App.js 26:6
Module parse failed: Unexpected token (26:6)
You may need an appropriate loader to handle this file type.
|   render() {
|     return (
>       <div className="App">
|         <header className="App-header2">
|         </header>
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! myapp@0.1.0 start: `webpack --config webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the myapp@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gregory\AppData\Roaming\npm-cache\_logs\2018-06-26T02_02_00_177Z-debug.log

C:\Users\Gregory\my-app>

**Comment by 0nePoint0ne** [comment]
I have used webpack before but I have never set it up. Any help would be appreciated

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babel-loader. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.

It's very hard to say what your issue is because you did not include your `webpack.config.js` content. In the future, please include as much information about your configuration as you can.
