### ISSUE TITLE
How can I stop from transform rest-spread operators

### ISSUE THREAD

**Issue by shuaiyaotian** [babel/babel-loader#636]
Chrome supports the feature object-rest-spread, I don't want to transform it in babel. 
But I got Syntax Error always, and the tips: "Add @babel/plugin-proposal-object-rest-spread (https://git.io/vb4Ss) to the 'plugins' section of your Babel config to enable transformation."

How to get around.

**Webpack Version:**
2.x

**Babel Core Version**:
7.x

**Babel Loader Version**:
8.x

**Comment by existentialism** [comment]
@shuaiyaotian even if you dont want to _transform_ rest-spread, you need to add `@babel/plugin-syntax-object-rest-spread` to your plugins inside your Babel config so that our parser can parse it. As a side note, `@babel/preset-env` takes care of this by default :)

**Comment by shuaiyaotian** [comment]
@existentialism Thank you.
After reading the source code, I realized that rest-spread must be transformed. I can't run code  without parsing it in browser, if I use babel.
disappointed~

**Comment by alex996** [comment]
@existentialism I don't understand... [Object Rest/Spread Properties](https://github.com/tc39/proposal-object-rest-spread) is already a [Stage 4](https://github.com/tc39/proposals/blob/master/finished-proposals.md) (Finished) proposal and is part of ES2018 spec. The same exact code runs fine in Chrome 68, but fails with `babel-loader`. Why is Babel still throwing `Support for the experimental syntax 'objectRestSpread' isn't currently enabled`? Is there plans to whitelist it anytime soon? Why or not? Otherwise, is there a way to enable it manually? Thanks

**Comment by nicolo-ribaudo** [comment]
It will be enabled by default by https://github.com/babel/babel/pull/8448. In the meantime, you can use `@babel/plugin-syntax-object-rest-spread`.
