### ISSUE TITLE
Spurious errors: `import '@babel/polyfill'` was not found.

### ISSUE THREAD

**Issue by wmertens** [babel/babel-loader#657]
**I'm submitting a feature request**

**Webpack Version:**
4

**Babel Core Version**:
7

**Babel Loader Version**:
next

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**

When using `useBuiltIns: "entry"`, every file that is compiled gets an error

```
...file: `import '@babel/polyfill'` was not found.
```

Since we're bundling files, it is normal that only one of them will have the polyfill.

**Expected/desired behavior:**

It would be great if this error was suppressed somehow, and only shown if nowhere in the resulting bundle `import '@babel/polyfill'` was found.

**Comment by pokkur** [comment]
+1

**Comment by loganfsmyth** [comment]
Hard to say without the full error message, but it sounds like the plugin never converted `@babel/polyfill` to `core-js/...`? Do you have `core-js` in your dependencies properly? It's hard to diagnose without a reproduction case.

**Comment by loganfsmyth** [comment]
I'm not sure there's anything we can do. That message only shows up when you've opted into debug logging from `preset-env`, so it's not an error. It just sounds like it is doing it's job. I think debug logging is just not useful unless you're explicitly looking for some specific thing. 

If you want to continue this discussion, let's move to https://github.com/babel/babel since this is not related to Webpack specifically.
