### ISSUE TITLE
Bump semver dependency to >= 7.5.2

### ISSUE THREAD

**Issue by aarona** [babel/babel-loader#994]
**Webpack Version:**
5.1.4 (listed as `"5"` in my `package.json`

**Babel Core Version**:
7.22.6

**Babel Loader Version**:
9.1.2

**Please tell us about your environment:**
Linux 5.15.0-76-generic #83~20.04.1-Ubuntu

**Current behavior:**
Failing `yarn audit` because it depends on an older version of `semver`.

**Expected/desired behavior:**
Dependence on `semver >= 7.5.2`

* **What is the motivation / use case for changing the behavior?**
It's causing my project's deployment to fail because dependency/audit job is failing and requires my dependencies to pass the audit.

**Comment by JoinThisBand** [comment]
I believe this is caused the same issue that impacted Angular earlier today: https://github.com/angular/angular-cli/issues/25496#issuecomment-1623604147

**Comment by Blacknight1260** [comment]
This is Robert Wilson. This Blacknight whatever is a hack job. And further I am contacting an attorney as my marriage has fallen apart due to this crap! I have asked google for help my bank account was used?!!! And not one person can tell me etc this is??? I do kit and have not used Amazon web site service.  Please assist to email stackwey123@hotmail.com.  If not I will contact attorney.  Robert Wilson
