### ISSUE TITLE
Vulnerable dependencies (indirect security issues)

### ISSUE THREAD

**Issue by RahatFatimah** [babel/babel-loader#997]
Hello maintainers,

I wanted to bring to your attention that after installing the package, I ran a vulnerability scan with vulert abom on the lock file and discovered that there are over 9 vulnerable dependencies present. As these vulnerabilities can potentially impact the security of the entire project, I am unsure whether to report this under responsible disclosure.

For your reference, here is a link to the report of the package-lock file I scanned: https://vulert.com/vuln-scan/list/e7c17d60-9b53-4c53-82ae-dfccf2e96b7d

I recommend that we take immediate action to address these vulnerabilities and ensure the security of the project. Please let me know if you require any further information.

P.S. this is the lock file i scanned: https://github.com/babel/babel-loader/blob/main/yarn.lock

Thank you.

**Comment by JLHwung** [comment]
As of now, the mentioned vulnerabilities all come from our `devDependencies`, because `npm audit` is happy with `dependencies`:

```
yarn npm audit --environment production --recursive
➤ YN0001: No audit suggestions
```

While we will eventually bump all our `devDependencies`, as an end user you can safely ignore the report, because our `devDependencies` will not be installed in your node modules.
